apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "aylee-front.fullname" .}}
  labels:
    {{- include "aylee-front.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    canary:
      {{- with .Values.canary.steps }}
      steps:
        {{- toYaml . | nindent 8}}
      {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimits }}
  selector:
    matchLabels:
      {{- include "aylee-front.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.istio.enabled }}
        {{- toYaml .Values.istio.annotations | nindent 8 }}
        {{- end}}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aylee-front.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aylee-front.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}